[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "meta-leap-research"
version = "0.1.0"
description = "Experiments for META-LEAP research paper."
authors = [{name = "AI Researcher", email = "researcher@example.com"}]

dependencies = [
    "torch>=2.1.0",
    "torch-geometric>=2.5.0",
    # GraphSAINT depends internally on SparseTensor which lives in the torch-sparse
    # package.  Add it explicitly so the loader can be built without runtime errors.
    "torch-sparse>=0.6.18",
    "ogb>=1.3.6",
    "transformers>=4.36.0",
    "scikit-learn>=1.3.0",
    "PyYAML>=6.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.13.0",
    "pynvml>=11.5.0",
    "scipy>=1.11.0",
    "pandas>=2.1.0",
    "tqdm>=4.66.0",
    "requests>=2.31.0"
]
