[project]
name = "aurora_experiment"
version = "0.1.0"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools", "wheel"]

[tool.poetry]
# If the autograder uses poetry, otherwise harmless
name = "aurora-experiment"
version = "0.1.0"
description = "AURORA discrete diffusion certification experiments"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.main.dependencies]
dependencies = [
  "pyyaml>=6.0",
  "numpy>=1.21.0",
  "torch>=1.9.0",
]
