[project]
name = "aurora_experiment"
version = "0.1.0"
requires-python = ">=3.9"
# Core runtime requirements – picked up by `pip` / PEP-517 installers
dependencies = [
  "pyyaml>=6.0",
  "numpy>=1.21.0",
  "torch>=1.9.0",
]

[build-system]
requires = ["setuptools", "wheel"]
