[tool.poetry]
name = "reflect-bo-research"
version = "0.1.0"
description = "Implementation of REFLECT-BO for research paper publication."
authors = ["AI Researcher"]

# Define a minimal stub package solely to satisfy Poetry’s packaging rules.
# All runnable scripts (main.py, train.py, etc.) live at project root and are
# executed directly; they are **not** imported as a library. Creating this stub
# prevents build failures without requiring a wholesale repository restructure.
packages = [
    { include = "reflect_bo_research" }
]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
torch = "2.1.0"
transformers = "4.39.0"
scikit-learn = "1.4.0"
pandas = "2.1.0"
numpy = "1.26.0"
openai = "1.3.0"
tiktoken = "0.5.0"
opacus = "1.4.0"
pykalman = "0.9.5"
streamlit = "1.30.0"
pyyaml = "6.0"
datasets = "2.16.0"
matplotlib = "3.8.0"
seaborn = "0.13.0"
accelerate = "0.25.0"
scipy = "1.11.3"

[project]
name = "reflect-bo-research"
version = "0.1.0"
description = "Implementation of REFLECT-BO for research paper publication."
requires-python = ">=3.11,<3.12"
authors = [{name = "AI Researcher"}]
license = {text = "MIT"}
readme = ""

# Minimal dependency list (duplicated from [tool.poetry] for PEP 621 compliance)
dependencies = [
    "torch==2.1.0",
    "transformers==4.39.0",
    "scikit-learn==1.4.0",
    "pandas==2.1.0",
    "numpy==1.26.0",
    "openai==1.3.0",
    "tiktoken==0.5.0",
    "opacus==1.4.0",
    "pykalman==0.9.5",
    "streamlit==1.30.0",
    "pyyaml==6.0",
    "datasets==2.16.0",
    "matplotlib==3.8.0",
    "seaborn==0.13.0",
    "accelerate==0.25.0",
    "scipy==1.11.3",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"