[project]
name = "zorropp-research"
version = "1.0.0"
description = "Experiments for ZORRO++ TTA method."
authors = [{name = "AI Researcher"}]

[project.dependencies]
dependencies = [
    "torch>=2.1.0",
    "torchvision>=0.16.0",
    "torchaudio>=2.1.0",
    "timm>=0.9.12",
    "transformers>=4.35.2",
    "datasets>=2.15.0",
    "pyyaml>=6.0.1",
    "pandas>=2.1.3",
    "numpy>=1.26.2",
    "scikit-learn>=1.3.2",
    "matplotlib>=3.8.2",
    "seaborn>=0.13.0",
    "wandb>=0.16.0",
    "py-nvml>=11.5.0",
    "fvcore>=0.1.6",
    "scipy>=1.11.4",
    "requests>=2.31.0",
    "huggingface-hub>=0.19.4",
    "opacus>=1.4.0",
    "tqdm>=4.66.1"
]
