# Full AURORA reproduction run – suitable for an 8×A100 node.
seed: 13

model:
  hidden: 256

training:
  epochs: 10
  lr: 5e-4
  batch_size: 64

data:
  dataset: "wikitext"
  split: "wikitext-103-raw-v1"  # legacy key – treated as HF *config* automatically
  tokenizer: "bert-base-uncased"
