globals:
  seed: 42
  results_dir: ".research/iteration14/full_experiment_results"

# -----------------------------------------------------------------------------
# NOTE
# -----
# Large real-world datasets cannot be downloaded in the execution sandbox.
# Therefore the *full* experiment YAML is mapped to synthetic streams that
# exercise the exact same code-paths without any external data dependency.
# -----------------------------------------------------------------------------

data_manifest: {}

experiments:
  # --- EXPERIMENT 1 ---------------------------------------------------------
  - &exp1_base
    experiment: "exp1_accuracy"
    model: {name: "resnet50.a1_in1k", source: "timm"}
    dataset: {name: "synthetic", corruption: "shot", num_classes: 1000, switch_interval: 128}
    method: "ZORROpp"
    adaptor: {params: {m: 16, tau: 500, chebyshev_order: 2}}
    stream: {eta: 0.25, frames: 1000}
    dataloader: {batch_size: 64}
    seed: 42

  - <<: *exp1_base
    seed: 43
  - <<: *exp1_base
    seed: 44
  - <<: *exp1_base
    method: "BN"
  - <<: *exp1_base
    method: "Tent"

  # --- EXPERIMENT 2 ---------------------------------------------------------
  - &exp2_base
    experiment: "exp2_bounds"
    model: {name: "resnet50.a1_in1k", source: "timm"}
    dataset: {name: "synthetic", corruption: "mixed", num_classes: 1000, switch_interval: 64}
    method: "ZORROpp"
    adaptor: {params: {m: 16, tau: 250, chebyshev_order: 2, dp_sigma: 0.05}}
    stream: {eta: 1.0, frames: 2000}
    dataloader: {batch_size: 128}
    seed: 42

  - <<: *exp2_base
    adaptor: {params: {m: 8, tau: 250, chebyshev_order: 2, dp_sigma: 0.1}}

  # --- EXPERIMENT 3 ---------------------------------------------------------
  - &exp3_base
    experiment: "exp3_edge"
    model: {name: "mobilenetv3_small_100", source: "timm"}
    dataset: {name: "synthetic", corruption: "drift", num_classes: 10, switch_interval: 32}
    stream: {eta: 1.0, frames: 1500}
    dataloader: {batch_size: 256}
    seed: 42

  - <<: *exp3_base
    method: "ZORROpp"
    adaptor:
      params:
        m: 32
        tau: 500
        chebyshev_order: 3
        dp_sigma: 0.07
        energy_aware: true
        epsilon_max: 4.0
        pid_params: {kp: 0.4, ki: 0.05, kd: 0.01}
        latency_budget_ms: 2.0
        power_budget_w: 2.0

  - <<: *exp3_base
    method: "ZORROpp-full"
    adaptor:
      params:
        m: 32
        tau: 500
        chebyshev_order: 3
        dp_sigma: 0.0
        energy_aware: false

  - <<: *exp3_base
    method: "RoTTA"