name: 'smoke_test_config'
experiment_to_run: 1

paths:
  secure_data_path: null
  processed_data_path: 'data/processed/smoke_test'
  training_output_path: '.research/iteration2/training/smoke_test'
  evaluation_output_path: '.research/iteration2/analysis/smoke_test'

api_details:
  provider: 'simulated'

model_names:
  encoder: 'cambridgeltl/trans-encoder-bi-simcse-roberta-base'
  generator: 'gpt-3.5-0613'
  scorer: 'gpt-4-0125'
  paraphraser: 'lmsys/vicuna-13b-v1.5'

seeds: [42]

experiment_1:
  datasets: []

experiment_2:
  methods: ['REFLECT-BO', 'REFLECT-BO-NoDP']
  total_prompts: 100

experiment_3:
  datasets: ['gsm8k']

optimization_params:
  api_budget: 5
  bootstrap_budget: 2

hyperparameters:
  learning_rate: [0.0003]
  bo_beta: [0.25]
  cvar_alpha: [0.9]

federated_params:
  n_clients: 2
  episodes: 1

dp_params:
  epsilon: 1.0
  delta: 1.0e-6
  noise_multiplier: 1.1
  max_grad_norm: 1.0

kalman_params:
  tau: [2.5]