name: 'smoke_test'
experiment_ids_to_run: [1] # Run only one experiment for a quick check

paths:
  # MIMIC-IV is a private dataset, path must be configured by user.
  # For smoke test, we rely on public data and skip this.
  mimic_iv_dir: '/tmp/mimic-iv-notes-dummy'
  processed_data_path: 'data/smoke_test'
  training_output_path: '.research/iteration12/training_smoke'

api_details:
  provider: 'huggingface' # Use local models to avoid API costs for testing

model_names:
  encoder: 'sentence-transformers/all-MiniLM-L6-v2' # Smaller encoder for speed
  generator: 'gpt2'
  scorer: 'gpt-4-0613' # Scorer is often critical, keep as specified but expect it to be mocked if key is absent
  paraphraser: 'tuner007/pegasus_paraphrase'
  continual_backend: 'gpt2'

seeds: [42]

# --- Experiment 1 Config ---
experiment_1:
  tasks: ['FinReg-Compliance']

# --- Experiment 2 Config ---
experiment_2:
  methods: ['REFLECT-BO', 'REFLECT-BO-NoDP']
  tasks: ['Super-NI']

# --- Experiment 3 Config ---
experiment_3:
  tasks: ['GSM8K']

sec_edgar_ciks: ['0000320193'] # Just Apple Inc. for a quick test

model_drift_schedule:
  - 'gpt2'
  - 'distilgpt2'

optimization_params:
  api_budget: 6
  bootstrap_budget: 2

hyperparameters:
  learning_rate: [0.0003]
  bo_beta: [0.25]
  cvar_alpha: [0.9]

federated_params:
  n_clients: 2
  episodes: 1

dp_params:
  epsilon: 1.0
  delta: 1.0e-6
  noise_multiplier: 1.1
  max_grad_norm: 1.0

kalman_params:
  tau: [2.5]