globals:
  seed: 42
  results_dir: ".research/iteration13/smoke_test_results"

data_manifest: {}

experiments:
  - experiment: "exp1_accuracy"
    model:
      name: "mobilenetv3_small_100"
      source: "timm"
    dataset:
      name: "synthetic"
      corruption: "mixed"  # not used for synthetic but kept for uniformity
      num_classes: 10
      switch_interval: 128
    method: "ZORROpp"
    adaptor:
      params:
        m: 8
        tau: 250
        chebyshev_order: 2
        dp_sigma: 0.0
        energy_aware: false
    stream:
      eta: 0.5
      frames: 100
    dataloader:
      batch_size: 32
    seed: 42

  - experiment: "exp1_accuracy"
    model:
      name: "mobilenetv3_small_100"
      source: "timm"
    dataset:
      name: "synthetic"
      corruption: "mixed"
      num_classes: 10
      switch_interval: 128
    method: "BN"
    stream:
      eta: 0.5
      frames: 100
    dataloader:
      batch_size: 32
    seed: 42